const text = [
  `Like dogs cats look very different from people but share many of our bodys characteristics such as a circulatory system lungs a digestive tract a nervous system and so on.`,
  `There are many different breeds of cats including Abyssinian Himalayan Maine Coon Manx Persian Scottish Fold and Siamese to name a few. The Cat Fanciers. Association which is the worlds largest registry of pedigreed cats recognizes about 40 distinct breeds.`,
  `The most familiar cats are the domestic shorthair and the domestic long hair which are really mixtures of different breeds. Cat breeds differ in looks, coat length, and other characteristics but vary relatively little in size. On average, only 5 to 10 pounds separate the smallest and largest domestic breeds of cats.`,
  `There are many different breeds of cats including Abyssinian Himalayan Maine Coon Manx Persian Scottish Fold and Siamese to name a few. The Cat Fanciers Association which is the worlds largest registry of pedigreed cats recognizes about 40 distinct breeds. The most familiar cats are the domestic shorthair and the domestic longhair which are really mixtures of different breeds. Cat breeds differ in looks coat length and other characteristics but vary relatively little in size. On average only 5 to 10 pounds separate the smallest and largest domestic breeds of cats.`,
  `Cats also share the rapid metabolism that dogs have which results in a higher heart rate respiratory rate and temperature than those of people. Cats generally live longer than dogs and many live to be 20 years old or older.`,
  `Cats are better at conserving heat than at cooling themselves although their small size relative to their large surface area makes for more effective cooling than in dogs.`,
  `Cats lose heat through external radiation. They have some sweat glands that aid in evaporative cooling and licking their fur further improves this process. Heat is also lost through panting although this is not as effective a method of cooling as it is in dogs. Cats typically also seek dark cool places to shelter themselves from the heat of the day. As with all animals cats should never be shut in cars or other hot confined spaces. This can lead to heat stroke and death.`,
  `Cats have the same 5 senses as people do but to very different degrees. Some senses are much better developed than in people.`,
  `Cats have keen vision; they can see much more detail than dogs. Concentrated in the center of the retina of the eye a specific type of cell called a cone gives cats excellent visual acuity and binocular vision. This allows them to judge speed and distance very well an ability that helped them survive as hunters. However although the cone cells are also responsible for color vision it is uncertain whether cats can see colors. Like dogs cats also have a lot of the retinal cells called rods which are good at collecting dim light. In fact cats can see 6 times better in dim light than people giving rise to the myth that cats can see in the dark. Cats also have a reflective layer called the tapetum lucidum which magnifies incoming light and lends a characteristic blue or greenish glint to their eyes at night.`,
  `A unique feature of both canine and feline eyes is the nictitating membrane which is also called the third eyelid. This additional eyelid is a whitish pink color and is found under the other eyelids in the inside corner (near the nose) of the eye. The third eyelid extends up when needed to protect the eyeball from scratches (such as while traveling through brush) or in response to inflammation.`,
  `Cats are very sensitive to sound with a range of hearing both above and below the range of frequencies that can be detected by people. They can hear better than people and even better than most dogs. Feline hearing also acts as a direction finder which is useful for hunting purposes. Cats generally turn their heads toward the direction of the sound while listening to pinpoint the location. The ear canal of cats is deeper and more tapered than in people. This deeper canal is subject to buildup of dirt and wax that can lead to inflammation and secondary infection although to a lesser degree than in dogs.`,
  `The semicircular canals which are found within the inner ear are filled with fluid and are important for maintaining balance. These are highly developed in cats accounting for their agility and excellent sense of balance. Cats can usually determine their body position at all times and can rapidly right themselves when falling which explains the origin of the phrase: Cats always land on their feet.`
];
export default text;
